ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "goodsAmount" DECIMAL(10,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "pointsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "pointsDiscount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "pointsRefundedAt" TIMESTAMP(3);
UPDATE "Order" SET "goodsAmount" = "amount" WHERE "goodsAmount" IS NULL;
