ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'UNPAID' BEFORE 'BOOKED';

ALTER TABLE "StudyBooking"
  ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
